---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Flowlogs'
Parameters:
  LogsDestinationType:
    Description: Select logs destination Type
    Default: S3
    Type: String
    AllowedValues:
      - S3
      - CloudWatch

  VPC:
    Description: 'Please mention VPC ID'
    Type: AWS::EC2::VPC::Id
  RetentionInDays:
    Description: 'Specifies the number of days you want to retain log events.'
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  TrafficType:
    Description: 'The type of traffic to log.'
    Type: String
    Default: REJECT
    AllowedValues:
    - ACCEPT
    - REJECT
    - ALL
Conditions:
  S3desttype: !Equals [ !Ref LogsDestinationType, S3 ]
  CWdesttype: !Equals [ !Ref LogsDestinationType, CloudWatch ]
Resources:
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'vpc-flow-logs.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: 'flowlogs-policy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            - 'logs:DescribeLogGroups'
            - 'logs:DescribeLogStreams'
            Resource: !GetAtt 'LogGroup.Arn'
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Join ['',['vpcflowlogs-',!Ref VPC]]
      RetentionInDays: !Ref RetentionInDays
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Condition: S3desttype
    Properties:
      BucketName: !Join ['',['vpcflowlogs-',!Ref VPC]]
  FlowLog:
    Type: 'AWS::EC2::FlowLog'
    Condition: S3desttype
    Properties:
      DeliverLogsPermissionArn: !GetAtt 'Role.Arn'
      LogDestination: !Ref 'S3Bucket'
      LogDestinationType: S3
      LogGroupName: !Ref LogGroup
      ResourceId: !Ref 'VPC'
      ResourceType: 'VPC'
      TrafficType: !Ref TrafficType
  FlowLog:
    Type: 'AWS::EC2::FlowLog'
    Condition: CWdesttype
    Properties:
      DeliverLogsPermissionArn: !GetAtt 'Role.Arn'
      LogGroupName: !Ref LogGroup
      ResourceId: !Ref 'VPC'
      ResourceType: 'VPC'
      TrafficType: !Ref TrafficType
Outputs:
  LogGroupName:
    Description: 'The name of the CloudWatch Logs log group where Amazon EC2 publishes your flow logs.'
    Value: !Ref LogGroup
  LogGroupARN:
    Description: 'The ARN of the CloudWatch Logs log group where Amazon EC2 publishes your flow logs.'
    Value: !GetAtt 'LogGroup.Arn'
  S3BucketName:
    Description: 'S3 Bucket Name for VPC Flow Logs'
    Condition: S3desttype
    Value: !Ref 'S3Bucket'
