---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates EC2 instances with Autoscaling, Load Balancer & Security Group
Parameters:
  BucketName:
    Description: The name
    Type: String
    Default: ''
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
    DeletionPolicy: Retain
  BucketRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - s3.amazonaws.com
  BucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:PutObject
          - s3:GetObject
          - s3:ListBucket
          - s3:CreateBucket
          Resource: arn:aws:s3:::${BucketName}
      PolicyName: BucketPolicy
      Roles:
      - BucketRole
Outputs:
  S3BucketSecureURL:
    Value: S3Bucket
    Description: Name of S3 bucket to hold website content
